# Generated by Django 5.2.4 on 2026-01-31 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('year', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=3, verbose_name="Niveau d'étude")),
                ('enrollment_status', models.CharField(choices=[('PENDING', 'En attente de validation'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=10, verbose_name="Statut d'inscription")),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('validated_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.department', verbose_name='Département')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('validated_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'DEPARTMENT_HEAD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Profil étudiant',
                'verbose_name_plural': 'Profils étudiants',
                'ordering': ['-enrollment_date'],
            },
        ),
    ]
