# Generated by Django 5.2.4 on 2026-01-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'emploi du temps")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=10, verbose_name='Statut')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année académique')),
                ('semester', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=20, verbose_name='Semestre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['-created_at'],
                'unique_together': {('academic_year', 'semester')},
            },
        ),
    ]
