# Generated by Django 5.2.4 on 2026-02-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_teacheravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la filière')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code de la filière')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='users.department', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du niveau (ex: Licence 1)')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code du niveau (ex: INFO-L1)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='users.filiere', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['code'],
            },
        ),
    ]
