# Generated by Django 5.2.4 on 2026-02-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_filiere_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='filiere',
        ),
        migrations.AddField(
            model_name='filiere',
            name='levels',
            field=models.ManyToManyField(related_name='filieres', to='users.level', verbose_name='Niveaux disponibles'),
        ),
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code du niveau (ex: L1)'),
        ),
    ]
