# Generated by Django 5.2.4 on 2026-01-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom de la salle')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacité')),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Salle de classe'), ('LAB', 'Laboratoire'), ('AMPHITHEATER', 'Amphithéâtre')], default='CLASSROOM', max_length=20, verbose_name='Type de salle')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localisation')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['name'],
            },
        ),
    ]
