# Generated by Django 5.2.4 on 2026-02-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_department_course_level_course_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Volume Horaire Total (Semestre)'),
        ),
    ]
