# Generated by Django 5.2.4 on 2026-02-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_total_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
