# Generated by Django 5.2.4 on 2026-02-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_department_remove_course_level'),
        ('users', '0003_filiere_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.level', verbose_name='Niveau'),
        ),
    ]
