# Generated by Django 5.2.4 on 2026-02-04 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_level'),
        ('users', '0004_remove_level_filiere_filiere_levels_alter_level_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.filiere', verbose_name='Filière'),
        ),
    ]
