# Generated by Django 5.2.4 on 2026-02-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheravailability',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin (Période)'),
        ),
        migrations.AddField(
            model_name='teacheravailability',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début (Période)'),
        ),
    ]
