# Generated by Django 5.2.4 on 2026-01-31 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        ('timetables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_slots', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='timetables.timetable', verbose_name='Emploi du temps'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('timetable', 'room', 'start_time', 'end_time')},
        ),
    ]
