# Generated by Django 5.2.4 on 2026-02-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='Jour')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('is_break', models.BooleanField(default=False, verbose_name='Est une pause')),
            ],
            options={
                'verbose_name': 'Plage Horaire Globale',
                'verbose_name_plural': 'Plages Horaires Globales',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
